## Perform vectorized implementation of simple matrix operation like finding the transpose of a matrix, adding, subtracting or multiplying two matrices. 

In [1]:
import numpy as np

# Create matrices
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Find the transpose of a matrix
m3 = np.transpose(m1)
print(m3)

# Add two matrices
m4 = m1 + m2
print(m4)

# Subtract two matrices
m5 = m1 - m2
print(m5)

# Multiply two matrices
m6 = np.dot(m1, m2)
print(m6)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
