## Perform basic operations on matrices (like addition, subtraction, multiplication) and display specific rows or columns of the matrix. 

In [1]:
import numpy as np

# Create matrices
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Matrix addition
m3 = m1 + m2
print(m3)

# Matrix subtraction
m4 = m1 - m2
print(m4)

# Matrix multiplication
m5 = np.dot(m1, m2)
print(m5)

# Display specific rows or columns of the matrix
print(m1[0, :])
print(m1[:, 1])

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[1 2 3]
[2 5 8]
