## Use command to compute the size of a matrix, size/length of a particular row/column, load data from a text file, store matrix data to a text file, finding out variables and their features in the current scope.

In [5]:
import numpy as np

# Create a matrix
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the size of the matrix
size = m1.size
print(size)

# Compute the size of a particular row/column
size_row = m1.shape
size_col = m1.shape[1]
print(size_row)
print(size_col)

# Load data from a text file
data = np.loadtxt("data.txt")
print(data)

# Store matrix data to a text file
np.savetxt("data.txt", m1)

# Finding out variables and their features in the current scope
var_list = dir()
print(var_list)

9
(3, 3)
3
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
['In', 'Out', '_', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_i2', '_i3', '_i4', '_i5', '_ih', '_ii', '_iii', '_oh', 'data', 'exit', 'get_ipython', 'm1', 'np', 'quit', 'size', 'size_col', 'size_row', 'var_list']
