## Perform other matrix operations like converting matrix data to absolute values, taking the negative of matrix values, additing/removing rows/columns from a matrix, finding the maximum or minimum values in a matrix or in a row/column, and finding the sum of some/all elements in a matrix. 

In [1]:
import numpy as np

# Create a matrix
m1 = np.array([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])

# Convert matrix data to absolute values
m2 = np.abs(m1)
print(m2)

# Take the negative of matrix values
m3 = -m1
print(m3)

# Add a row to the matrix
m4 = np.vstack([m1, [10, -11, 12]])
print(m4)

# Remove a row from the matrix
m5 = np.delete(m1, 1, axis=0)
print(m5)

# Find the maximum value in the matrix
max_val = np.max(m1)
print(max_val)

# Find the minimum value in the matrix
min_val = np.min(m1)
print(min_val)

# Find the sum of all elements in the matrix
sum_all = np.sum(m1)
print(sum_all)

# Find the sum of elements in a row/column
sum_row = np.sum(m1, axis=1)
sum_col = np.sum(m1, axis=0)
print(sum_row)
print(sum_col)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1  2 -3]
 [ 4 -5  6]
 [-7  8 -9]]
[[  1  -2   3]
 [ -4   5  -6]
 [  7  -8   9]
 [ 10 -11  12]]
[[ 1 -2  3]
 [ 7 -8  9]]
9
-8
5
[ 2 -5  8]
[ 4 -5  6]
