## Create/Define single dimension / multi-dimension arrays, and arrays with specific values like array of all ones, all zeros, array with random values within a range, or a diagonal matrix. 

In [1]:
import numpy as np

# Create a single dimension array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Create a multi-dimension array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)

# Create an array of all ones
arr3 = np.ones((3, 4))
print(arr3)

# Create an array of all zeros
arr4 = np.zeros((2, 3))
print(arr4)

# Create an array with random values within a range
arr5 = np.random.randint(0, 10, (2, 3))
print(arr5)

# Create a diagonal matrix
arr6 = np.diag([1, 2, 3])
print(arr6)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[6 8 6]
 [6 2 5]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
